import Button from '@/components/Button/Button';
import Htag from '@/components/Htag/Htag';
import P from '@/components/P/P';
import Rating from '@/components/Rating/Rating';
import Tag from '@/components/Tag/Tag';
import withLayout from '@/layout/Layout';
import Head from 'next/head';
import { useState } from 'react';

function Home() {
  const [rating, setRating] = useState<number>(4);
  return (
    <>
      <Head>
        <title>MyTop - наш лучший топ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="preconnect" href="https://mc.yandex.ru" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Htag tag="h1">Заголовок 1</Htag>
        <Htag tag="h2">Заголовок 2</Htag>
        <Htag tag="h3">Заголовок 3</Htag>

        <Button appearance="ghost">Кнопка1</Button>
        <Button appearance="primary">Кнопка2</Button>
        <Button appearance="ghost" arrow="down">
          Кнопка3
        </Button>
        <Button appearance="ghost" arrow="right">
          Кнопка3
        </Button>

        <P size="l">Параграф1</P>
        <P>Параграф2</P>
        <P size="s">Параграф3</P>

        <Tag color="ghost">ghost</Tag>
        <Tag color="red">red</Tag>
        <Tag color="grey">grey</Tag>
        <Tag color="green">green</Tag>
        <Tag color="primary">primary</Tag>

        <Rating rating={rating} isEditable setRating={setRating} />
      </div>
    </>
  );
}

export default withLayout(Home);
